### ISSUE TITLE
extglob

### ISSUE THREAD

**Issue by erikkemperman** [jonschlinkert/to-absolute-glob#3]
``` js
var tag = require('to-absolute-glob');
tag('!(foo)'); // !/abs/path/(foo)
```

Was it silly of me to expect `/abs/path/!(foo)` instead?

**Comment by jonschlinkert** [comment]
maybe, it's an ambiguous pattern. The correct way to define that would probably be `tag('\\!(foo)')`

edit: since parens are completely valid path characters, and `!` might be a leading (full-path) negation pattern or, since it precedes a parentheses, might indicate a negation extglob, IMO it should be escaped to make it clear that it's an extglob pattern, if that's what you want. Otherwise, if it's not an extglob, don't escape it

**Comment by erikkemperman** [comment]
Thanks for the quick response!

That seems eminently reasonable, but does it mesh with how the PR in glob-stream proposes to use both is-negated-glob and to-absolute-glob, at present?

For instance, how would I tell glob-stream to match any file in `/abs/path/` except for `foo`?

**Comment by erikkemperman** [comment]
I should add to the above: with the path in the `cwd` option, not in the pattern. I.e., neither of these does the job:

``` js
var gs = require('glob-stream');
gs('!(foo)', { cwd: '/abs/path' });
gs('\\!(foo)', { cwd: '/abs/path' });
```

**Comment by jonschlinkert** [comment]
> For instance, how would I tell glob-stream to match any file in /abs/path/ except for foo?

`/abs/path/!(foo)`?

**Comment by jonschlinkert** [comment]
also, If we were talking about micromatch, I would be surprised, but that pr removes micromatch. so all matching is done with minimatch, which fails on like 30% of extglobs. e.g. this is probably a moot discussion unless that changes. I believe of the tests relevant to this library are passing.

**Comment by erikkemperman** [comment]
Yeah, so the problem -- if that's what is -- happens when the extglob is at the beginning; hence my addendum above.

No doubts that this library does what it advertises, and is-negated-glob likewise, but I wondered if they're mutually consistent, as juxtaposed by glob-stream now.

The way that either of the above glob-stream calls end up constructing args for node-glob seems off to me, and I've confirmed that node-glob does what I expect (at least for these cases) if I construct its args myself:

``` js
var g = require('glob').sync;
g('/abs/path/!(foo)'); // [ /abs/path/bar ]
```

(the dir has two files, `foo` and `bar`).

Anyway, I guess it's unlikely to cause real trouble. Just curious. Thanks a lot for getting back to me!

**Comment by jonschlinkert** [comment]
Are you just saying we need to implement `is-negated-glob` to be consistent? If so I think that's a good idea -  when I mentioned on glob-stream that I wanted to use is-negated-glob in other places, this is one of them.

**Comment by erikkemperman** [comment]
Yes, and I think that would mean an unescaped extglob would then be resolved like I expected at the top of this thread.

It'd be a breaking change here though, for these edge cases anyway. Also, glob-stream would effectively be running is-negated-glob twice for each pattern.

It's not pretty I guess, but what if to-absolute-glob (in addition to strings) accepted the output object from is-negated-glob directly? Or conversely if is-negated-glob had an option to resolve to absolute?

**Comment by erikkemperman** [comment]
Then again, running is-negated-glob twice is of course completely insignificant relative to the fs operations it will do, so that last bit may just be complicating things needlessly.

**Comment by erikkemperman** [comment]
So clearly I have too much time on my hands, in between projects at work...

But might it look something like this?
https://github.com/erikkemperman/to-absolute-glob/commit/299cb8b76fa58949f319f6dfab64aa2de43b2df5

If so, it would "fix" something like the following test in glob-stream, to the extent that it's "broken" now:
https://github.com/erikkemperman/glob-stream/commit/dd47dad14ed2ac2d65b0e20882e5899f1a9a9752

**Comment by jonschlinkert** [comment]
> But might it look something like this?

that looks good, want to do a pr?

**Comment by erikkemperman** [comment]
Yup, [done](https://github.com/jonschlinkert/to-absolute-glob/pull/6).

I considered briefly if it would make sense to merge the two repos into `parse-glob`, or something like that, to avoid the (miniscule) duplication now incurred by glob-stream. But I guess it'd run counter to the "do one thing, do it well" mantra.
