### ISSUE TITLE
Windows tests on AppVeyor

### ISSUE THREAD

**Issue by phated** [jonschlinkert/to-absolute-glob#5]
I think testing on Windows CI would be very helpful, especially while I am trying to wrap my head around the root stuff in this module (which doesn't seem to take Windows drives into account).

**Comment by jonschlinkert** [comment]
> which doesn't seem to take Windows drives into account

Was there a specific issue that needs to be resolved? We can implement support for whatever is causing issues. AppVeyor is a good idea too

**Comment by doowb** [comment]
Closing since appveyor was added in #8

**Comment by phated** [comment]
What is the link to the AppVeyor results?

**Comment by phated** [comment]
Found it: https://ci.appveyor.com/project/jonschlinkert/to-absolute-glob

**Comment by doowb** [comment]
I'll get the readme updated with the appveyor badge too

**Comment by phated** [comment]
PR submitted 😉

**Comment by jonschlinkert** [comment]
thanks!
